# Generated by Django 5.2.15 on 2026-10-08 03:02

import django.db.models.deletion
import inventree_nfc_scanner.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventree_nfc_scanner", "0002_scannercounter"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Firmware",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=40, unique=True)),
                ("prerelease", models.BooleanField(default=False)),
                (
                    "source",
                    models.CharField(
                        choices=[("github", "GitHub release"), ("upload", "Uploaded")],
                        max_length=8,
                    ),
                ),
                ("release_url", models.URLField(blank=True, max_length=300)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("manifest", models.JSONField()),
                ("proto", models.PositiveIntegerField()),
                ("settings_version", models.PositiveIntegerField()),
                ("min_plugin", models.CharField(max_length=40)),
                (
                    "app",
                    models.FileField(
                        blank=True,
                        max_length=200,
                        upload_to=inventree_nfc_scanner.models.firmware_path,
                    ),
                ),
                ("app_size", models.PositiveIntegerField()),
                ("app_sha256", models.CharField(max_length=64)),
                (
                    "merged",
                    models.FileField(
                        blank=True,
                        max_length=200,
                        upload_to=inventree_nfc_scanner.models.firmware_path,
                    ),
                ),
                ("merged_size", models.PositiveIntegerField(blank=True, null=True)),
                ("merged_sha256", models.CharField(blank=True, max_length=64)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Scanner firmware",
                "verbose_name_plural": "Scanner firmware",
                "ordering": ["-published_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="Scanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reader_id", models.CharField(max_length=32, unique=True)),
                ("fw", models.CharField(blank=True, max_length=40)),
                ("proto", models.PositiveIntegerField(blank=True, null=True)),
                ("boot", models.PositiveIntegerField(blank=True, null=True)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                (
                    "last_via",
                    models.CharField(
                        blank=True,
                        choices=[("network", "Network"), ("usb", "USB")],
                        max_length=8,
                    ),
                ),
                (
                    "last_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "NFC scanner (fleet)",
                "verbose_name_plural": "NFC scanners (fleet)",
                "ordering": ["reader_id"],
            },
        ),
        migrations.CreateModel(
            name="Deployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "required",
                    models.BooleanField(
                        blank=True,
                        help_text="Whether a USB user may put it off; empty: the plugin's policy",
                        null=True,
                    ),
                ),
                (
                    "required_after",
                    models.DateTimeField(
                        blank=True,
                        help_text="No longer deferrable from this time",
                        null=True,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("downloading", "Downloading"),
                            ("restarting", "Restarting"),
                            ("confirmed", "Confirmed"),
                            ("failed", "Failed"),
                            ("rolled_back", "Rolled back"),
                            ("superseded", "Superseded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "via",
                    models.CharField(
                        blank=True,
                        choices=[("network", "Network"), ("usb", "USB")],
                        max_length=8,
                    ),
                ),
                ("from_version", models.CharField(blank=True, max_length=40)),
                ("boot_at_start", models.PositiveIntegerField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("retry_after", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("deferrals", models.PositiveIntegerField(default=0)),
                ("last_deferred_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.CharField(blank=True, max_length=32)),
                ("detail", models.CharField(blank=True, max_length=200)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "firmware",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deployments",
                        to="inventree_nfc_scanner.firmware",
                    ),
                ),
                (
                    "scanner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deployments",
                        to="inventree_nfc_scanner.scanner",
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at", "-pk"],
            },
        ),
    ]
